name: ci-trivy-demo

on:
  push:
    paths:
      - "devsecops-trivy-demo/**"
      - ".github/workflows/ci-trivy-demo.yml"
  pull_request:
    paths:
      - "devsecops-trivy-demo/**"
      - ".github/workflows/ci-trivy-demo.yml"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-trivy-demo
  cancel-in-progress: true

jobs:
  build-test-scan:
    runs-on: ubuntu-24.04
    env:
      PYTHONPATH: ${{ github.workspace }}/devsecops-trivy-demo  # <- pour que 'app' soit importable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install deps
        working-directory: devsecops-trivy-demo
        run: pip install -r requirements.txt

      - name: Tests
        working-directory: devsecops-trivy-demo
        run: python -m pytest -q        # <- python -m pytest + PYTHONPATH règle le import 'app'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (local)
        uses: docker/build-push-action@v6
        with:
          context: devsecops-trivy-demo  # <- sous-dossier
          push: false
          load: true
          tags: devsecops-demo:${{ github.sha }}

      - name: Trivy FS scan (info)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: devsecops-trivy-demo
          trivy-config: devsecops-trivy-demo/trivy.yaml
          format: table
          exit-code: '0'

      - name: Trivy Image scan (bloquant)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: devsecops-demo:${{ github.sha }}
          trivy-config: devsecops-trivy-demo/trivy.yaml
          format: table
          exit-code: '1'
          vuln-type: 'os,library'
