name: zap-baseline-dvwa
on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/zap-dvwa.yml"
  pull_request:
    paths:
      - ".github/workflows/zap-dvwa.yml"

jobs:
  zap:
    runs-on: ubuntu-latest
    services:
      dvwa:
        image: vulnerables/web-dvwa
        ports:
          - 8080:80
    steps:
      - uses: actions/checkout@v4
      - name: Wait for DVWA
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8080 >/dev/null; then
              echo "DVWA is up"; break; fi; sleep 2; done
      - name: ZAP Baseline
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "http://localhost:8080"
          cmd_options: "-r zap_report.html"
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: zap_report.html
